# Explicitly tell Nixpacks this is a Python app
[phases.setup]
aptPkgs = ["tesseract-ocr", "libreoffice"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "sh -c 'alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:$PORT app.main:app'"
